version: '3.8'

services:
  backend:
    image: jefzimmer/antt-multas-backend:v.0.0.1
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    environment:
      NODE_ENV: production
    networks:
      - network_swarm_public
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.ant-multas-backend.rule=Host(`extratormultas.rodoxisto.com.br`) && PathPrefix(`/api`)
        - traefik.http.routers.ant-multas-backend.entrypoints=websecure
        - traefik.http.routers.ant-multas-backend.tls.certresolver=letsencryptresolver
        - traefik.http.services.ant-multas-backend.loadbalancer.server.port=3000
      resources:
        limits:
          cpus: "1"
          memory: 512M
      placement:
        constraints:
          - node.role == manager

  frontend:
    image: jefzimmer/antt-multas-frontend:v.0.0.1
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    environment:
      - VITE_GOOGLE_MAPS_API_KEY_FILE=/run/secrets/google_maps_api_key
    secrets:
      - google_maps_api_key
    networks:
      - network_swarm_public
    depends_on:
      - backend
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.ant-multas-frontend.rule=Host(`extratormultas.rodoxisto.com.br`)
        - traefik.http.routers.ant-multas-frontend.entrypoints=websecure
        - traefik.http.routers.ant-multas-frontend.tls.certresolver=letsencryptresolver
        - traefik.http.services.ant-multas-frontend.loadbalancer.server.port=80
      resources:
        limits:
          cpus: "1"
          memory: 512M
      placement:
        constraints:
          - node.role == manager

networks:
  network_swarm_public:
    external: true

secrets:
  google_maps_api_key:
    external: true 